/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poly.cafe.ui;

import poly.cafe.ui.PolyCafeController.PolyCafeController;
import poly.cafe.util.XIcon;

/**
 *
 * @author hang
 */
public class PolyCafeJFrame extends javax.swing.JFrame implements PolyCafeController {

    /**
     * Creates new form PolyCafeJFrame
     */
    public PolyCafeJFrame() {
        initComponents();
        this.init();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        btnHistory1 = new javax.swing.JButton();
        btnSales = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnDrinkManager = new javax.swing.JButton();
        btnBillManager = new javax.swing.JButton();
        btnCategoryManager = new javax.swing.JButton();
        btnUserManager = new javax.swing.JButton();
        btnCardManager = new javax.swing.JButton();
        btnRevenueManager = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        lblFullname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 300, 10));

        btnHistory1.setText("LỊCH SỬ");
        btnHistory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistory1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistory1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 114, 37));

        btnSales.setText("BÁN HÀNG");
        btnSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesActionPerformed(evt);
            }
        });
        getContentPane().add(btnSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 114, 37));

        btnChangePassword.setText("ĐỔI MẬT KHẨU");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });
        getContentPane().add(btnChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 37));

        btnExit.setText("KẾT THÚC");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 114, 37));

        btnDrinkManager.setText("ĐỒ UỐNG");
        btnDrinkManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrinkManagerActionPerformed(evt);
            }
        });
        getContentPane().add(btnDrinkManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 130, 37));

        btnBillManager.setText("PHIẾU BÁN HÀNG");
        btnBillManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillManagerActionPerformed(evt);
            }
        });
        getContentPane().add(btnBillManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 130, 37));

        btnCategoryManager.setText("LOẠI ĐỒ UỐNG");
        btnCategoryManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryManagerActionPerformed(evt);
            }
        });
        getContentPane().add(btnCategoryManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 360, 130, 37));

        btnUserManager.setText("NGƯỜI SỬ DỤNG");
        btnUserManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserManagerActionPerformed(evt);
            }
        });
        getContentPane().add(btnUserManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 420, 130, 37));

        btnCardManager.setText("THẺ ĐỊNH DANH");
        btnCardManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardManagerActionPerformed(evt);
            }
        });
        getContentPane().add(btnCardManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, 130, 37));

        btnRevenueManager.setText("DOANH THU");
        getContentPane().add(btnRevenueManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 420, 130, 37));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee-shop.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 0, 790, 470));

        lblPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trump-small.png"))); // NOI18N
        getContentPane().add(lblPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 120, 150));

        lblFullname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFullname.setText("Trần Anh Đức");
        getContentPane().add(lblFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalesActionPerformed

    private void btnHistory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistory1ActionPerformed
        // TODO add your handling code here:
        this.showHistoryJDialog(this);
    }//GEN-LAST:event_btnHistory1ActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.exit();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDrinkManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrinkManagerActionPerformed
        // TODO add your handling code here:
        this.showCategoryManagerJDialog(this);
    }//GEN-LAST:event_btnDrinkManagerActionPerformed

    private void btnCardManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardManagerActionPerformed
        // TODO add your handling code here:
        this.showCardManagerJDialog(this);
    }//GEN-LAST:event_btnCardManagerActionPerformed

    private void btnUserManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserManagerActionPerformed
        // TODO add your handling code here:
        this.showUserManagerJDialog(this);
    }//GEN-LAST:event_btnUserManagerActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // TODO add your handling code here:
        this.showChangePasswordJDialog(this);
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnBillManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillManagerActionPerformed
        // TODO add your handling code here:
        this.showBillManagerJDialog(this);
    }//GEN-LAST:event_btnBillManagerActionPerformed

    private void btnCategoryManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryManagerActionPerformed
        // TODO add your handling code here:
        this.showDrinkManagerJDialog(this);
    }//GEN-LAST:event_btnCategoryManagerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolyCafeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolyCafeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolyCafeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolyCafeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PolyCafeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBillManager;
    private javax.swing.JButton btnCardManager;
    private javax.swing.JButton btnCategoryManager;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnDrinkManager;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHistory1;
    private javax.swing.JButton btnRevenueManager;
    private javax.swing.JButton btnSales;
    private javax.swing.JButton btnUserManager;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFullname;
    private javax.swing.JLabel lblPhoto;
    // End of variables declaration//GEN-END:variables

    @Override
    public void init() {
        this.setIconImage(XIcon.getIcon("C:\\Users\\hang\\Documents\\NetBeansProjects\\PoLyCaFe\\src\\main\\resources\\trump-small.png").getImage());
        this.setLocationRelativeTo(null);

        this.showWelcomeJDialog(this);
        this.showLoginJDialog(this);

        if (XAuth.isManager()) {
            XIcon.setIcon(lblPhoto, XAuth.user.getPhoto());
            lblFullname.setText(XAuth.user.getFullname());

        } else {
            XIcon.setIcon(lblPhoto, XAuth.user.getPhoto());
            lblFullname.setText(XAuth.user.getFullname());
            btnDrinkManager.setVisible(false);
            btnCategoryManager.setVisible(false);
            btnCardManager.setVisible(false);
            btnBillManager.setVisible(false);
            btnUserManager.setVisible(false);
            btnRevenueManager.setVisible(false);
        }
    }

}
